---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

grails:
    mail:
        protocol: smtps
        host: smtp.gmail.com
        port: 465
        username: donotreplypropertyui@gmail.com
        password: rkckusccvinkcyeh
        props: [ 'mail.smtps.starttls.enable':'true',
                 'mail.smtp.auth': 'true',
                 'mail.smtp.sicketFactory.port': '465',
                 'mail.smtp.socketFactory.class': 'javax.net.ssl.SSLSocketFactory',
                 'mail.smtp.socketFactory.fallback': 'false']

application:
    defaultCacheInvalidate: 600000 #Every 1o minutes
    mail:
        logo:
        name: "Property UI"
        from:
            confirmation:
                name: "Property UI"
                email: "donotreplypropertyui@gmail.com"
            resetPassword:
                name: "Reset Password Property UI"
                email: "donotreplypropertyui@gmail.com"
            contactUs:
                name: "Property UI"
                email: "donotreplypropertyui@gmail.com"
            support:
                name: "Property UI"
                email: "donotreplypropertyui@gmail.com"
    propertyUi:
        baseUrl: http://localhost:8080


environments:
    development:
        dataSource:
            dbCreate: update
#            dialect: com.propertyui.dialect.MySQLUTF8InnoDBDialect
            driverClassName: com.mysql.jdbc.Driver
            username: root
            password:
            url: jdbc:mysql://127.0.0.1:3306/propertyui?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
            logSql: false
            properties:
                dbProperties:
                    autoReconnect: true
                    zeroDateTimeBehavior: convertToNull
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

---
---
grails:
    profile: web
    codegen:
        defaultPackage: propertyui
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:

    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true
